<?php

Class Nganh extends GeneralSeeder
{
    public $table = 'Nganh';
    public $data = array(
        array('MaNganh' => 1, 'TenNganh' => 'Bán hàng'),
        array('MaNganh' => 2, 'TenNganh' => 'Báo chí/Biên tập viên'),
        array('MaNganh' => 3, 'TenNganh' => 'Bất động sản'),
        array('MaNganh' => 4, 'TenNganh' => 'Biên dịch/Phiên dịch'),
        array('MaNganh' => 5, 'TenNganh' => 'Bưu chính viễn thông'),
        array('MaNganh' => 6, 'TenNganh' => 'Cơ khí/Kĩ thuật ứng dụng'),
        array('MaNganh' => 7, 'TenNganh' => 'Công nghệ thông tin'),
        array('MaNganh' => 8, 'TenNganh' => 'Dầu khí/Địa chất'),
        array('MaNganh' => 9, 'TenNganh' => 'Dệt may'),
        array('MaNganh' => 10, 'TenNganh' => 'Bảo vệ/Vệ sĩ/An ninh'),
        array('MaNganh' => 11, 'TenNganh' => 'Chăm sóc khách hàng'),
        array('MaNganh' => 12, 'TenNganh' => 'Điện/Điện tử/Điện lạnh'),
        array('MaNganh' => 13, 'TenNganh' => 'Du lịch/Nhà hàng/Khách sạn'),
        array('MaNganh' => 14, 'TenNganh' => 'Dược/Hóa chất/Sinh hóa'),
        array('MaNganh' => 15, 'TenNganh' => 'Giải trí/Vui chơi'),
        array('MaNganh' => 16, 'TenNganh' => 'Giáo dục/Đào tạo/Thư viện'),
        array('MaNganh' => 17, 'TenNganh' => 'Giao thông/Vận tải/Thủy lợi/Cầu đường'),
        array('MaNganh' => 18, 'TenNganh' => 'Giày da/Thuộc da'),
        array('MaNganh' => 19, 'TenNganh' => 'Hành chính/Thư ký/Trợ lý'),
        array('MaNganh' => 20, 'TenNganh' => 'Kho vận/Vật tư/Thu mua'),
        array('MaNganh' => 21, 'TenNganh' => 'Kiến trúc/Nội thất'),
        array('MaNganh' => 22, 'TenNganh' => 'Kinh doanh'),
        array('MaNganh' => 23, 'TenNganh' => 'Lao động phổ thông'),
        array('MaNganh' => 24, 'TenNganh' => 'Luật/Pháp lý'),
        array('MaNganh' => 25, 'TenNganh' => 'Sinh viên/Mới tốt nghiệp/Thực tập'),
        array('MaNganh' => 26, 'TenNganh' => 'Môi trường/Xử lý chất thải'),
        array('MaNganh' => 27, 'TenNganh' => 'Mỹ phẩm'),
        array('MaNganh' => 28, 'TenNganh' => 'Ngân hàng/Chứng khoán/Đầu tư'),
        array('MaNganh' => 29, 'TenNganh' => 'Nghệ thuật/Điện ảnh'),
        array('MaNganh' => 30, 'TenNganh' => 'Nhân sự'),
        array('MaNganh' => 31, 'TenNganh' => 'Nông/Lâm/Ngư nghiệp'),
        array('MaNganh' => 32, 'TenNganh' => 'Quan hệ đối ngoại'),
        array('MaNganh' => 33, 'TenNganh' => 'Thẩm định/Giám định/Quản lý chất lượng'),
        array('MaNganh' => 34, 'TenNganh' => 'Quản lý điều hành'),
        array('MaNganh' => 35, 'TenNganh' => 'Quảng cáo/Marketing/PR'),
        array('MaNganh' => 36, 'TenNganh' => 'Sản xuất/Vận hành sản xuất'),
        array('MaNganh' => 37, 'TenNganh' => 'Tài chính/Kế toán/Kiểm toán'),
        array('MaNganh' => 38, 'TenNganh' => 'Thể dục/Thể thao'),
        array('MaNganh' => 39, 'TenNganh' => 'Thiết kế/Mỹ thuật'),
        array('MaNganh' => 40, 'TenNganh' => 'Thời vụ/Bán thời gian'),
        array('MaNganh' => 41, 'TenNganh' => 'Thực phẩm/DV ăn uống'),
        array('MaNganh' => 42, 'TenNganh' => 'Xây dựng'),
        array('MaNganh' => 43, 'TenNganh' => 'Xuất-Nhập khẩu/Ngoại thương'),
        array('MaNganh' => 44, 'TenNganh' => 'Y tế'),
        array('MaNganh' => 45, 'TenNganh' => 'Khác'),
        array('MaNganh' => 46, 'TenNganh' => 'Ngoại ngữ'),
        array('MaNganh' => 47, 'TenNganh' => 'Khu chế xuất/Khu công nghiệp'),
        array('MaNganh' => 48, 'TenNganh' => 'Làm đẹp/Thể lực/Spa'),
        array('MaNganh' => 49, 'TenNganh' => 'Tài xế/Lái xe/Giao nhận'),
        array('MaNganh' => 50, 'TenNganh' => 'Trang thiết bị công nghiệp'),
        array('MaNganh' => 51, 'TenNganh' => 'Trang thiết bị gia dụng'),
        array('MaNganh' => 52, 'TenNganh' => 'Trang thiết bị văn phòng'),
        array('MaNganh' => 53, 'TenNganh' => 'Tư vấn bảo hiểm'),
        array('MaNganh' => 54, 'TenNganh' => 'PG/PB/Lễ tân'),
        array('MaNganh' => 55, 'TenNganh' => 'Phát triển thị trường'),
        array('MaNganh' => 56, 'TenNganh' => 'Phục vụ/Tạp vụ/Giúp việc'),
    );
}